name: docker-hub-description

on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/docker-hub-description.yml
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository_owner }}/dnsmasq-leases-ui
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
